version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
   
   
  # mongo-express:
  #   image: mongo-express
  #   #restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password

  # distancecalculator.shell:
  #   image: ${REGISTRY:-orange}/distancecalculator:${PLATFORM:-linux}-${TAG:-latest}
  #   container_name: distancecalculator
  #   ports:
  #     - 5000:5000
  #     - 5001:5001
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   build:
  #     context: .
  #     dockerfile: src/Services/DistanceCalculator/DistanceCalculator.Shell/Dockerfile

  # airportinfo.shell:
  #   image: ${REGISTRY:-orange}/airportinfo:${PLATFORM:-linux}-${TAG:-latest}
  #   container_name: airportinfo
  #   ports:
  #     - 9000:6000
  #     - 6001:6001
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - mongo
  #   build:
  #     context: .
  #     dockerfile: src/Services/AirportInfo/AirportInfo.Shell/Dockerfile
   
