version: '3.4'

services:
  nginx-lb:
    image: nginx
    container_name: nginx-lb
    restart: always #unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/ApiGateways/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/ApiGateways/nginx/config/certificates/:/etc/ssl/:ro

  mongo:
    image: mongo
    container_name: mongo-nosql
    ports:
     - 27017:27017
    #volumes:
    #  - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-exp
    restart: always
    ports:
      - 34081:8081

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-tr
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

  distancecalculator:
    image: ${REGISTRY:-orange}/distancecalculator:${PLATFORM:-linux}-${TAG:-latest}
    container_name: distancecalculator
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AirportInfoClientConfig__BaseAddress=https://nginx-lb/api/v1
    depends_on:
      - airportinfo
    build:
      context: .
      dockerfile: src/Services/DistanceCalculator/DistanceCalculator.Shell/Dockerfile

  airportinfo:
    image: ${REGISTRY:-orange}/airportinfo:${PLATFORM:-linux}-${TAG:-latest}
    container_name: airportinfo
    ports:
      - 7000:7000
      - 7001:7001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://mongo/?keepAlive=true&minPoolSize=5&maxPoolSize=300&autoReconnect=true&socketTimeoutMS=3600&connectTimeoutMS=3600&compressors=zstd
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: src/Services/AirportInfo/AirportInfo.Shell/Dockerfile 
